fail_fast: true

repos:
  - repo: local
    hooks:
      - id: spellcheck
        name: spellcheck
        entry: bash scripts/check-spelling.sh
        language: system

  - repo: local
    hooks:
      - id: taggeneration
        name: taggeneration
        entry: python scripts/tag_generator.py
        language: python

